### PR TITLE
Enable path to python to be set with options.pythonPath.

### PR DESCRIPTION
**Pull request by gwu**

### CODE REVIEW

**Comment by jmendiara** [comment]
I really like this approach in general. However, a few things have to change to get it to land.
* [Test](https://github.com/jmendiara/node-closure-linter-wrapper/blob/master/test/closure-linter-wrapper_test.js#L17) should pass
* Document pythonPath in this [Readme section](https://github.com/jmendiara/node-closure-linter-wrapper#documentation)

Does that sound reasonable to you?

**Comment by gwu** [comment]
Yes, I will try to get this done in the next few days.

**Comment by gwu** [comment]
Fixed the broken test and added a note to the README. Please let me know if there are other changes you'd like me to make.

**Comment by jmendiara** [comment]
Released as v1.0.0 

Thanks @gwu !

**Pull request merged**
